---
title: 'Stocks and Bonds: Risks and Returns'
author: "Attila Doroszlai"
date: '2014-10-29'
output: html_document
---

```{r}
bond_price <- function(years, coupon.rate, ytm, face.value = 1000, freq = 2) {
  periods <- years * freq
  payment <- rep(coupon.rate * face.value / freq, periods)
  payment[periods] <- payment[periods] + face.value
  sum(payment / (1 + ytm / freq)^(1:periods))
}
```

## 1.4.5.1

`r bond_price(years = 5, coupon.rate = 0.018, ytm = 0.022)`

## 1.4.5.2

`r bond_price(years = 8, coupon.rate = 0.018, ytm = 0.022)`

## 1.4.5.3

`r bond_price(years = 5, coupon.rate = 0.025, ytm = 0.022)`

## 1.4.5.4

`r bond_price(years = 5, coupon.rate = 0.018, ytm = 0.032)`

## 1.6.1

```{r}
r <- c(0.0013, 0.0039, 0.0079, 0.0121, 0.0162)
p <- c(50, 50, 50, 50, 1050)
sum(p / (1 + r)^(1:5))
```

```{r}
percent <- function(x, digits = 1) {
  cat(format(100 * x, digits = digits), '%', "\n")
}
```

## 5.2.2.1

`r 80000/100000`

## 5.2.2.2

`r 150000/100000`

## 5.2.3.1

```{r}
t <- c(5, 5)
r <- c(0.155, -0.045)
b <- 2

# 5.2.3.1.a
arithmetic_mean_return <- sum(r * b * t) / sum(t)
percent(arithmetic_mean_return, digits = 1)

# 5.2.3.1.b
compound_annualized_return <- prod((1 + r * b)^t) ^ (1 / sum(t)) - 1
percent(arithmetic_mean_return - compound_annualized_return, digits = 2)
```

## 5.2.3.2

```{r}
r <- c(0.16, 0.06, -0.04, -0.16)
t <- 2
ignored <- sapply(c(1, 5), function(b) {
  # 5.2.3.2 (beta = 1), 5.2.3.4 (beta = 5)
  arithmetic_mean_return <- mean(r * b)
  percent(arithmetic_mean_return, digits = 2)
  
  # 5.2.3.3 (beta = 1), 5.2.3.5 (beta = 5)
  outcomes <- (r+1) %*% t((r+1)) - 1
  favorable <- sum(outcomes >= arithmetic_mean_return)
  prob <- favorable / length(outcomes)
  percent(prob, 0)
})
```

## 5.2.4.1

```{r}
rf <- 0.01 # risk-free rate
rp <- 0.055 # market risk premium
vol <- 0.17 # annual

calculate <- function(b) {
  cat("Expected return: ")
  percent(rf + b * rp, digits = 3)
  
  cat("Standard Deviation: ")
  percent(b * vol, digits = 3)
  
  cat("Sharpe ratio: ", format(rp / vol, digits = 2))
}

beta = 0.7
calculate(beta)
```

## 5.2.4.2

```{r}
beta = 1.2
calculate(beta)
```